[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http"]
[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 3333
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true