[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
[dev]
  command = "vite"
  port = 3333
  targetPort = 5173
  publish = "dist"
  autoLaunch = true
[[redirects]]
  from = "/api/*"
to = "/.netlify/functions/api/api/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
