[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http"]
[dev]
  command = "vite"
  port = 3333
  targetPort = 5173
  publish = "dist"
  autoLaunch = true
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
