[functions]
directory = "netlify/functions"
external_node_modules = ["express"]
node_bundler = "esbuild"

[dev]
command = "vite"
port = 3333
targetPort = 5173
publish = "public"

# ✅ Place API route rules first!
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
from = "/test"
to = "/.netlify/functions/api/test"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200