[dev]
command = "npm run dev"
  targetPort = 3333 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
[serve]
[functions]
  directory = "functions"
  external_node_modules = ["express", "esbuild", "lightningcss"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
command = "npm run build"
publish = "dist"
functions = "functions"
