[dev]
command = "npm run dev"
  targetPort = 3333 # The port for your application server, framework or site generator
  port = 3334 # The port that the netlify dev will be accessible on
  directory = "functions/"

[serve]

[functions]
  external_node_modules = ["express", "esbuild", "lightningcss"]
  node_bundler = "esbuild"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
