[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[dev]
  framework = "#custom"
  command = "vite"
  targetPort = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
