[dev]
command = "npm run dev"
  targetPort = 5173 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on

[functions]
  external_node_modules = ["express", "esbuild", "lightningcss"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  to = "/netlify/functions/api/:splat"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

