[dev]
command = "npm run dev"
  targetPort = 5173 # The port for your application server, framework or site generator
  port = 3333 # The port that the netlify dev will be accessible on
    directory = "functions/"
[serve]
[functions]
  external_node_modules = ["express", "esbuild", "lightningcss"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
