[dev]
command = "npm run dev"
targetPort = 5173  # Must match your environment variable
port = 3334  # Netlify Dev port
  directory = "netlify/functions/"

[functions]
  external_node_modules = ["express", "esbuild", "lightningcss"]
  node_bundler = "esbuild"
[[redirects]]
  from = "/api/*"
  to = "/functions/api/:splat"
  status = 200
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [build]
  functions = "functions/"